### ISSUE TITLE
Alarm notification not coming when app is in killed mode

### ISSUE THREAD

**Issue by yogi535** [daniel-iroka/Todo-List#1]
Alarm notifications are coming during killed mode in android pixel emulator , but during check on vivo , samsung physical device its not coming on killed mode

**Comment by daniel-iroka** [comment]
@yogi535 Hello, thanks for the feedback. Please can you clarify the issue on this 'killed mode'. I don't know what that is, I've never heard of that and also what is the android version of the vivo and Samsung devices you mentioned, thank you.

**Comment by daniel-iroka** [comment]
@yogi535 I use a Redmi 8a(physical device) which is an Android 9 and the Notifications work perfectly but I think you need to first enable the "Show notifications" for the App's Notification feature to work(in killed mode too). If you've done that already and it's still not working(without autostart) then that must be because you did not build the Apk of this project as I suspect this may be the issue https://stackoverflow.com/a/64101916/14329945
